"""Default Release 1 permission assignments for stable LMS roles."""

RELEASE1_ROLE_PERMISSIONS = {
    "student": {
        "courses.view",
        "course_structure.view",
        "materials.view",
        "calendar.view",
    },
    "teacher": {
        "courses.view",
        "courses.create",
        "courses.edit",
        "courses.submit_review",
        "course_structure.view",
        "course_structure.manage",
        "materials.view",
        "materials.upload",
        "materials.edit",
        "materials.delete",
        "enrollments.view",
        "calendar.view",
        "calendar.manage",
    },
    "teaching_assistant": {
        "courses.view",
        "course_structure.view",
        "course_structure.manage",
        "materials.view",
        "materials.upload",
        "materials.edit",
        "enrollments.view",
        "calendar.view",
    },
    "content_manager": {
        "courses.view",
        "courses.create",
        "courses.edit",
        "courses.delete",
        "courses.submit_review",
        "courses.review",
        "courses.publish",
        "courses.copy",
        "course_structure.view",
        "course_structure.manage",
        "materials.view",
        "materials.upload",
        "materials.edit",
        "materials.delete",
        "calendar.view",
        "calendar.manage",
    },
    "lms_admin": "*",
    "super_admin": "*",
}
