# Generated by Django 4.2.20 on 2026-08-14 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("learning", "0005_scormpackage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progress",
                        to="learning.lesson",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson progress",
                "verbose_name_plural": "Lesson progress",
                "ordering": ("-updated_at", "-id"),
            },
        ),
        migrations.AddConstraint(
            model_name="lessonprogress",
            constraint=models.UniqueConstraint(
                fields=("student", "lesson"),
                name="progress_unique_student_lesson",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonprogress",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("completed_at__isnull", True),
                        ("started_at__isnull", True),
                        ("status", "not_started"),
                    ),
                    models.Q(
                        ("completed_at__isnull", True),
                        ("started_at__isnull", False),
                        ("status", "in_progress"),
                    ),
                    models.Q(
                        ("completed_at__isnull", False),
                        ("started_at__isnull", False),
                        ("status", "completed"),
                    ),
                    _connector="OR",
                ),
                name="progress_status_timestamps_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonprogress",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("completed_at__isnull", True),
                    ("completed_at__gte", models.F("started_at")),
                    _connector="OR",
                ),
                name="progress_completion_not_before_start",
            ),
        ),
    ]
