# Generated by Django 4.2.20 on 2026-04-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="tuition_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Tuition fee per semester in KGS",
                max_digits=10,
            ),
        ),
    ]
