# Generated by Django 4.2.20 on 2026-04-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_methodologist",
            field=models.BooleanField(default=False),
        ),
    ]
