# Generated by Django 4.2.20 on 2026-07-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_seed_release1_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
