# Generated by Django 4.2.20 on 2026-08-06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("language", models.CharField(choices=[("en", "English"), ("ky", "Kyrgyz"), ("ru", "Russian")], default="en", max_length=10)),
                ("credits", models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ("status", models.CharField(choices=[("draft", "Draft"), ("under_review", "Under review"), ("published", "Published"), ("archived", "Archived")], db_index=True, default="draft", max_length=20)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("cover", models.ImageField(blank=True, upload_to="courses/covers/")),
                ("syllabus", models.FileField(blank=True, upload_to="courses/syllabi/")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_created", to=settings.AUTH_USER_MODEL)),
                ("department", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="courses", to="organization.department")),
                ("faculty", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="courses", to="organization.faculty")),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="courses", to="organization.program")),
                ("semester", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="courses", to="organization.semester")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(app_label)s_%(class)s_updated", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "ordering": ("code",),
                "indexes": [
                    models.Index(fields=["semester", "status"], name="course_sem_status_idx"),
                    models.Index(fields=["faculty", "status"], name="course_fac_status_idx"),
                ],
            },
        ),
    ]
