# Generated by Django 5.2.7 on 2026-09-05 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursetemplate'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='organization.group'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['group', 'status'], name='course_grp_status_idx'),
        ),
    ]
