# Generated by Django 4.2.20 on 2026-08-14 10:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_course_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('release_type', models.CharField(choices=[('always', 'Always'), ('after_previous', 'After previous'), ('date', 'Date')], default='always', max_length=20)),
                ('release_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course module',
                'verbose_name_plural': 'Course modules',
                'ordering': ('course', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='learning.coursemodule')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course topic',
                'verbose_name_plural': 'Course topics',
                'ordering': ('module', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('lesson_type', models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('material', 'Material'), ('mixed', 'Mixed'), ('external_link', 'External link')], default='text', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('release_type', models.CharField(choices=[('always', 'Always'), ('after_previous', 'After previous'), ('after_lesson', 'After lesson'), ('date', 'Date')], default='always', max_length=20)),
                ('release_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('required_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dependent_lessons', to='learning.lesson')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.coursetopic')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ('topic', 'order', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('topic', 'order'), name='learning_unique_lesson_order'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(check=models.Q(('order__gte', 1)), name='learning_lesson_order_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('release_at__isnull', False), ('release_type', 'date'), ('required_lesson__isnull', True)), models.Q(('release_at__isnull', True), ('release_type', 'after_lesson'), ('required_lesson__isnull', False)), models.Q(('release_type__in', ('always', 'after_previous')), ('release_at__isnull', True), ('required_lesson__isnull', True)), _connector='OR'), name='learning_lesson_release_fields'),
        ),
        migrations.AddConstraint(
            model_name='coursetopic',
            constraint=models.UniqueConstraint(fields=('module', 'order'), name='learning_unique_topic_order'),
        ),
        migrations.AddConstraint(
            model_name='coursetopic',
            constraint=models.CheckConstraint(check=models.Q(('order__gte', 1)), name='learning_topic_order_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='coursemodule',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='learning_unique_module_order'),
        ),
        migrations.AddConstraint(
            model_name='coursemodule',
            constraint=models.CheckConstraint(check=models.Q(('order__gte', 1)), name='learning_module_order_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='coursemodule',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('release_at__isnull', False), ('release_type', 'date')), models.Q(models.Q(('release_type', 'date'), _negated=True), ('release_at__isnull', True)), _connector='OR'), name='learning_module_release_fields'),
        ),
    ]
