# Generated by Django 4.2.20 on 2026-08-14 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_course_lifecycle'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'DOC'), ('docx', 'DOCX'), ('ppt', 'PPT'), ('pptx', 'PPTX'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('external_link', 'External link'), ('library_link', 'Library link'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(blank=True, upload_to='learning/materials/')),
                ('external_url', models.URLField(blank=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('extension', models.CharField(blank=True, max_length=20)),
                ('download_allowed', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_materials', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='learning.lesson')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning material',
                'verbose_name_plural': 'Learning materials',
                'ordering': ('lesson', 'id'),
                'indexes': [models.Index(fields=['course', 'type'], name='learn_material_course_type')],
            },
        ),
    ]
