# Generated by Django 4.2.20 on 2026-08-14 11:49

from django.db import migrations, models
import learning.storage


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_learningmaterial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningmaterial",
            name="file",
            field=models.FileField(
                blank=True,
                storage=learning.storage.material_storage,
                upload_to="learning/materials/",
            ),
        ),
    ]
