# Generated by Django 4.2.20 on 2026-08-14 12:03

from django.db import migrations, models


def mark_existing_videos_ready(apps, schema_editor):
    del schema_editor
    learning_material = apps.get_model("learning", "LearningMaterial")
    learning_material.objects.filter(type="video").exclude(file="").update(
        video_status="ready"
    )


def clear_existing_video_statuses(apps, schema_editor):
    del schema_editor
    learning_material = apps.get_model("learning", "LearningMaterial")
    learning_material.objects.filter(type="video").update(
        video_status="",
        duration_seconds=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_alter_learningmaterial_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningmaterial",
            name="duration_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="learningmaterial",
            name="video_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("uploaded", "Uploaded"),
                    ("processing", "Processing"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                max_length=20,
            ),
        ),
        migrations.RunPython(
            mark_existing_videos_ready,
            clear_existing_video_statuses,
        ),
    ]
