# Generated by Django 4.2.20 on 2026-08-14 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import learning.storage


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_lifecycle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0004_learningmaterial_duration_seconds_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScormPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        storage=learning.storage.material_storage,
                        upload_to="learning/scorm/",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("version", models.CharField(blank=True, max_length=50)),
                ("launch_path", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scorm_packages",
                        to="courses.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scorm_packages",
                        to="learning.lesson",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SCORM package",
                "verbose_name_plural": "SCORM packages",
                "ordering": ("lesson", "id"),
                "indexes": [
                    models.Index(
                        fields=["course", "status"], name="learn_scorm_course_status"
                    )
                ],
            },
        ),
    ]
