# Generated by Django 4.2.20 on 2026-04-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleitem",
            name="room",
            field=models.CharField(
                blank=True,
                help_text="Номер кабинета / аудитории",
                max_length=50,
                null=True,
            ),
        ),
    ]
